name: frontend
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  flame: ^1.15.0
  url_launcher: ^6.0.2
  sqflite: ^2.3.0
  flutter_svg: ^2.0.10+1
  wheel_chooser: ^1.1.2
  go_router: ^14.2.1
  intl: ^0.19.0
  dartchess: any
  async:
  sqflite_aurora:
    git:
      url: https://gitlab.com/omprussia/flutter/flutter-plugins.git
      ref: sqflite_aurora-0.5.0
      path: packages/sqflite/sqflite_aurora
  flame_svg: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/pieces/
    - assets/images/small_pieces/
    - assets/images/icons/
    - assets/images/guide_boards/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
